import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import Footer from '../components/Footer'
import { useTheme } from '../components/ThemeContext'
import Nav from '../components/Nav'

const basePath = '/metastudio.id'

const Home: NextPage = () => {
  const darkTheme = useTheme()

  return (
    <>
      <div className={`${darkTheme.dark ? 'dark' : 'light'}`}>
        <div className='font-hindSiliguri bg-white dark:bg-black mt-0'>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href={`${basePath}/favicon.ico`} />
          </Head>

          <div className='min-h-screen container mx-auto max-w-8xl'>
            <Nav/>
            <div className='md:flex grid md:min-h-fit'>
              <div className='px-5 pt-3 order-2 md:order-1 text-center md:text-left md:pt-24 text-black dark:text-white'>
                <h2 className='text-4xl font-bold leading-snug md:text-7xl md:leading-tight md:max-w-xl md:mr-40'>
                  Digital Art Is The Trend Today
                </h2>
                <h5 className='font-medium text-lg mt-2 opacity-60 md:mt-5 md:text-3xl md:max-w-xl md:leading-tight md:my-4'>Metastudio is your full-service NFT&apos;s development partner. We&apos;re here to help you sell your Arts.</h5>
                <button className='mt-4 text-lg drop-shadow-2xl hover:drop-shadow-xl bg-gradient-to-r from-fuchsia-600 via-purple-600 to-sky-600 text-white font-bold px-5 py-4 rounded-full md:mt-6'>
                  Launch Your Own NFT&apos;s Project
                </button>
              </div>
              <div className='pt-5 order-1 md:order-2'>
                <img className='drop-shadow-2xl w-4/5 mx-auto md:w-11/12 md:mt-1' src={`${basePath}/images/banner1.png`} />
              </div>
            </div>
          </div>

          <div className='pt-5 text-center md:container md:mx-auto text-black dark:text-white'>
            <h3 className='text-3xl px-6 font-medium leading-snug md:text-6xl md:leading-tight'>
              NFT Minting Page and<br /> Landing Page Development
            </h3>
            <p className='px-10 text-base my-4 pb-9 font-medium opacity-60 md:pb-0 md:text-2xl md:max-w-5xl md:mx-auto md:mt-7 md:leading-snug'>
              Your don&apos;t need to touch the code. Let Metastudio do it for you. The Trusted partner in high volume, best-in class NFT development on the Solana Blockchain.
            </p>
            <img className='w-4/5 mx-auto mt-8 md:mt-28 drop-shadow-2xl' src={`${basePath}/images/banner2.png`} />
          </div>

          <div className='bg-gradient-art bg-cover text-center text-white py-20 md:text-left'>
            <div className='md:container md:mx-auto md:flex md:justify-between'>
              <div className='pt-2 md:py-40'>
                <h3 className='text-3xl px-6 font-medium leading-snug md:text-7xl md:leading-tight md:max-w-xl md:px-0'>
                  Art Engine:<br />
                  NFT Artworks Creation
                </h3>
                <p className='px-10 text-base my-4 font-medium opacity-80 md:text-3xl md:px-0 md:max-w-xl md:leading-normal'>
                  We&apos;re here to help you create thousand difference instance of artworks based on provided layers.
                </p>
              </div>
              <div className='pb-2 md:mt-40'>
                <img className='w-4/5 mx-auto mt-5 drop-shadow-2xl md:w-full' src={`${basePath}/images/banner3.png`} />
              </div>
            </div>
          </div>
          <Footer/>
        </div>
      </div>
    </>
  )
}

export default Home
